# Generated by Django 4.1.4 on 2023-01-02 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='promocao',
            field=models.BooleanField(default=False),
        ),
    ]
